const taskDefs = [
  {
    name: 'TRD_TMS_TRANSPORT',
    retryCount: 100,
    timeoutSeconds: 0,
    inputKeys: ['orderId', 'tripId', 'statuses', 'completeTransport', 'cancelWorkflow'],
    outputKeys: ['orderId', 'tripId', 'statuses', 'cancelWorkflow', 'staffId', 'completeTransport'],
    timeoutPolicy: 'RETRY',
    retryLogic: 'FIXED',
    retryDelaySeconds: 0,
    responseTimeoutSeconds: 1,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_CREATE_TASKS',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orders', 'orderId', 'statuses', 'mainWorkflowInstantId'],
    outputKeys: ['tasks', 'orderId', 'statuses'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 5,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_CREATE_TRIP',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orderId', 'tasks', 'statuses', 'mainWorkflowInstantId', 'orderMetadata'],
    outputKeys: [
      'tripId',
      'orderId',
      'statuses',
      'driverCriteria',
      'broadcastConfig',
      'vehicleType',
    ],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 5,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TMS_MAPPING_BASE_MODEL_FOR_DELIVERY',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orders', 'orderId', 'statuses'],
    outputKeys: ['orders', 'orderId', 'statuses'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 5,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_FLEET_FIND_DRIVER',
    retryCount: 0,
    timeoutSeconds: 240,
    inputKeys: [
      'orderId',
      'orderMetadata',
      'tripId',
      'driverCriteria',
      'statuses',
      'broadcastConfig',
      'passengerId',
    ],
    outputKeys: [
      'orderMetadata',
      'staffId',
      'tripId',
      'statuses',
      'broadcastUserIds',
      'broadcastId',
      'orderId',
      'vehicleId',
    ],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 10,
    responseTimeoutSeconds: 1,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_FLEET_GET_USER_CREATE_TASK_TRIP_WORKSCHEDULE',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orderId', 'staffId', 'tripId', 'statuses', 'vehicleId', 'orderMetadata'],
    outputKeys: ['statuses', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_CANCEL_DRIVER',
    retryCount: 0,
    timeoutSeconds: 3600,
    inputKeys: [
      'orderId',
      'trip',
      'tasks',
      'staffId',
      'passengers',
      'workflowInstanceId',
      'orderMetadata',
      'orderStatus',
    ],
    outputKeys: ['statuses', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_DELETE_TRIP_TASK_TODOS',
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
    inputKeys: [],
    outputKeys: [],
  },
  {
    name: 'TRD_TMS_SUMMARY',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orderId', 'tripId', 'staffId', 'statuses', 'orderMetadata'],
    outputKeys: ['orderId', 'tripId', 'staffId', 'statuses', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_CANCEL_FLOW',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['tripId', 'staffId', 'orderId', 'statuses', 'cancelBy', 'orderMetadata'],
    outputKeys: ['tripId', 'staffId', 'orderId', 'statuses', 'cancelBy', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_CREATE_TASKS_BY_TASKTYPE',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orders', 'orderId', 'statuses', 'mainWorkflowInstantId', 'orderMetadata'],
    outputKeys: ['tasks', 'orderId', 'statuses', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 5,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_DISPATCH_OPTIMIZE',
    retryCount: 3,
    timeoutSeconds: 3600,
    inputKeys: ['orders', 'orderId', 'statuses', 'mainWorkflowInstantId', 'orderMetadata'],
    outputKeys: ['tasks', 'orderId', 'statuses', 'orderMetadata'],
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 5,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
  },
  {
    name: 'TRD_TMS_DELETE_TRIP_TASK_TODOS',
    timeoutPolicy: 'TIME_OUT_WF',
    retryLogic: 'FIXED',
    retryDelaySeconds: 60,
    responseTimeoutSeconds: 3600,
    ownerEmail: '4pl-tms-owner@true-e-logistics.com',
    inputKeys: [],
    outputKeys: [],
  },
]
export default taskDefs
