export const TicketProductType92 = {
  ticket: {
    recNo: '1',
    ticketNo: '1',
    actvNo: '1',
    prodId: '9610010312',
    prodType: '92-DSTV-Satellite-Demo',
    createDate: '2021-01-21T14:25:31+07:00',
    category: '08-แจ้งเสีย',
    subCategory: '01-Connectไม่ได้',
    solution: '032-ไฟ PON ไม่ติด /ไฟ LOS สีแดง',
    appointDate: '2017-04-17T13:00:00+07:00',
    targetDate: '2020-06-13T10:00:00+07:00',
    rcu: 'CMI15X0000Q',
    org: 'TRUE|TRUE|AREA_USAN|UPC_NORTH|NORTH_1|NORTH_1:1',
    contName: 'Test Migrate',
    contMobile: '0123456789',
    custAddr: '77/177, -, -, -, -, -, บ้านแหวน, หางดง, เชียงใหม่, 50230',
    transFrom: 'TRUE|AREA_USAN|UPC_NORTH|NORTH_1|NORTH_1:1',
    transTo: 'TRUE|TEMP',
    reason: 'T03-หาบ้านผู้เช่าไม่พบ-No Access',
    transDate: '2017-04-12T14:35:01+07:00',
    flag: 'T-TRANSFER',
    systemDate: '2017-04-12T14:35:01+07:00',
    ticketRefNo: '2-534572453',
    voPortPosition: '',
    relateData: '9600413500',
    relateVoice: '025001029',
    relateVideo: '144094741',
    media: 'GPON',
    latitude: '',
    longitude: '',
    addrId: '231027688',
    areaCd: '500108000000',
    preferAppntDate: '0001-01-01T00:00:00Z',
    appntNo: 'eee5f842-b4fd-4200-9893-26229ad3a054',
    networkCatalog: '92',
    serviceType: '0809058QN',
    readFlag: 'N',
    ticketInfo: {
      accntPriority: 'Blue',
      actnType: 'CREATE',
      actvNumber: '1',
      actvStatus: 'O',
      apQty: 0,
      apXFerID: '01017306',
      apXFerOrgName: 'TRUE|NOC',
      apXFerReason: 'T00|มาจากสร้างเหตุเสีย',
      cab: 'BKK17X0604K:1/1',
      category: '08|แจ้งเสีย',
      contactEmail: 'craynei@gmail.com',
      contactMobile1: '0896697100',
      contactName: 'คุณ เกาะกูด แสมสาร',
      createDate: '12052020214057',
      createID: '01017306|THERTKIAT INTARAKOSIT',
      createOrgName: 'TRUE|NOC',
      customerName: 'Test Migrate',
      dp: 'BKK17X0604L:1/7',
      expectSla: 24,
      idCD: '2787819635487',
      installAddress:
        '147, ซอย ร.ร.หัสดิเสวี, ถ.สุทธิสาร, ห้วยขวาง, ห้วยขวาง, กรุงเทพมหานคร, 10310',
      latitude: '13.786681',
      lineClassCD: 'N',
      longitude: '100.57886',
      naQty: 0,
      oltEquipment: 'BKK17001G00',
      openDate: '12052020214057',
      orgName: 'TRUE|AREA_USAN|RNSO_BMA|BMA05|BMA05-7',
      param: [
        'Related Data:9610010312',
        'Related Voice:',
        'Related Video:108140831',
        'Media:GPON',
        'LoID:1804019135',
        'Package:null',
        'OrgBrief:AREA',
        'AppointNO:',
        'WorkOrderNO:',
        'AddressID:231027688',
        'AreaCD:101701040000',
        'SiteName:BKK17001',
        'OdfNo:NTB04X1DV2K',
        'DwellingType:A - Sub install with dropwire : OUTDOOR TEMINAL',
        'DropWire:1.0',
        'Ban:200060391',
        'WfmSystem:WFM',
        'Function:null',
        'Installed Onu:null',
        'Supported Onu:ZTE',
        'PreferAppointDate:null',
        'Priceplan Speed:1G/100M',
        'Shuffle Speed:null',
        'Vas Speed:null',
        'Radius Speed:1G/100M',
      ],
      productCategory: '74|Fiber To Home',
      productID: '9610010312',
      productLine: 'TrueOnline',
      queueCD: 'R',
      rcu: 'BKK17001G00',
      remainTime: '-0021:20:47',
      remarkDate: '13052020151207',
      remarkDtl: 'Create Job on WFM not success',
      remarkID: 'WFM1111|WFM',
      remarkOrgName: 'TRUE|SERVICE',
      repairDate: '12052020214057',
      returnCode: '0-00000',
      returnDescription: 'Success',
      returnSystem: 'CFM',
      rrQty: 17,
      serviceClassCD: 'R',
      serviceLevel: 'R N (24)',
      severity: '4-Low',
      sla: 24,
      solution: '036|หลุดบ่อย ค่าสัญญาณดี',
      splitterL1: 'BKK17X0604K',
      splitterL2: 'BKK17X0604L',
      ssQty: 0,
      subCategory: '02|Connectได้แต่มีปัญหา',
      targetDate: '13052020214057',
      ticketNumber: '20200512213959923142',
      ticketOwner: 'CFMWEB',
      ticketPosition: 'A',
      ticketStatus: 'O',
      workUnitID: '101701040000',
      xferDate: '12052020214057',
      xferRoute: 'CREATE',
      accntLevel: '',
      ackDate: '',
      ackID: '',
      ackOrgName: '',
      ackStatus: '',
      actionDate: '',
      actionID: '',
      actionType: '',
      appointDate: '',
      bbCardSpec: '',
      bbCardType: '',
      bbCardVendor: '',
      bbEquipmentClliCD: '',
      bbNetworkClliCD: '',
      bbOutDoorDslamFlag: '',
      bbPort: '',
      bbPortStatus: '',
      bbPortStatusDesc: '',
      bbRack: '',
      bbShelf: '',
      bbShelfPosition: '',
      bbSlot: '',
      card: '',
      causeCD1: '',
      causeCD2: '',
      cfmTucProductSmsResponseBean: [],
      cfmTucProductVcareResponseBean: [],
      clliCodeOlt: '',
      closeDate: '',
      closeID: '',
      closeLocation: '',
      closeOrgName: '',
      completeDate: '',
      contactMobile2: '',
      contactTel: '',
      cusTicketNumber: '',
      datCD: '',
      dispositionCD1: '',
      dispositionCD2: '',
      distCabDp: 0,
      distDw: 0,
      distRcuCab: 0,
      dpLocation: '',
      dpPair: '',
      draft: '',
      ds: '',
      es: '',
      eventNO: '',
      eventType: '',
      fiber: '',
      maxSpeed: '',
      neSsiNO: '',
      noAccessDate: '',
      pcCD: '',
      pcPair: '',
      port: '',
      productStatus: '',
      rcuName: '',
      readson1: '',
      reason2: '',
      scCD: '',
      scPair: '',
      slot: '',
      specialNote: '',
      subReason1: '',
      subReason2: '',
      summary: '',
      techID1: '',
      techID2: '',
      telNO: '',
      telStatus: '',
      ticketRefNumber: '',
      tpDat: '',
      ttDesc: '',
      tucRemark: '',
      voCardSpec: '',
      voCardType: '',
      voCardVendor: '',
      voEquipmentClliCD: '',
      voNetworkClliCD: '',
      voOutdoorDslamFlag: '',
      voPort: '',
      voPortStatus: '',
      voPortStatusDesc: '',
      voRack: '',
      voShelf: '',
      voShelfPosition: '',
      voSlot: '',
      voidIpAddress: '',
      wfDate: '',
      wfID: '',
      wfStatus: '',
      workCD1: '',
      workCD2: '',
      shelf: '',
    },
    clsOfSrvCd: 'R',
    lineClsCd: 'F',
    sla: 24,
    ss: 0,
    rr: 0,
    exchngId: '',
    queue: 'A',
    accessTypes: ['HSI', 'FLP', 'FIBERTV'],
    contTel: '',
    bbShelfName: '',
    bbCardPosition: '',
    voShelfName: '',
    voCardPosition: '',
    distRcuCab: 0,
    distCabDp: 0,
    distDw: 0,
  },
};
